import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const userSchema = mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    password: {
      type: String,
      required: true,
    },
    isAdmin: {
      type: Boolean,
      required: true,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

//the matchPassword is called on the registered user(this)
userSchema.methods.matchPassword = async function (enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

userSchema.pre('save', async function (next) {
  //bcrypt shouldn't run if the user modifies his name or email
  //this part of mongoose
  if (!this.isModified('password')) {
    next(); //if nothing has been modified then move on(next)
  }

  const salt = await bcrypt.genSalt(10);
  //this.password is the password generated by the new user who's about to be saved in DB
  this.password = await bcrypt.hash(this.password, salt);
});

const User = mongoose.model('User', userSchema);

export default User;
